#!/usr/bin/env python3
import sys
from rqt_gui.main import Main

from my_gui_pacjage.gui import GUI

plugin = 'my_gui_pacjage.gui.GUI'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))
